#if !defined(INCLUDE_ARRAY_MACROS_INTERFACE_FLXY_H)
#define INCLUDE_ARRAY_MACROS_INTERFACE_FLXY_H

// This file is generated by tools/define_arrays.py

#if NDIMS == 2
// [1 : isize+0], [1 : jsize+1]
#define FLXY(I, J) (flxy[(I-1) + (isize+0) * (J-1)])
#define FLXY_NADDS (int [NDIMS][2]){ {0, 0}, {0, 1}, }
#endif

#if NDIMS == 3
// [1 : isize+0], [1 : jsize+1], [1 : ksize+0]
#define FLXY(I, J, K) (flxy[(I-1) + (isize+0) * ((J-1) + (jsize+1) * (K-1))])
#define FLXY_NADDS (int [NDIMS][2]){ {0, 0}, {0, 1}, {0, 0}, }
#endif

#endif // INCLUDE_ARRAY_MACROS_INTERFACE_FLXY_H
