#if !defined(INCLUDE_ARRAY_MACROS_INTERFACE_FLXZ_H)
#define INCLUDE_ARRAY_MACROS_INTERFACE_FLXZ_H

// This file is generated by tools/define_arrays.py

// [1 : isize+0], [1 : jsize+0], [1 : ksize+1]
#define FLXZ(I, J, K) (flxz[(I-1) + (isize+0) * ((J-1) + (jsize+0) * (K-1))])
#define FLXZ_NADDS (int [NDIMS][2]){ {0, 0}, {0, 0}, {0, 1}, }

#endif // INCLUDE_ARRAY_MACROS_INTERFACE_FLXZ_H
