#if !defined(ARRAYS_INTERFACE_H)
#define ARRAYS_INTERFACE_H

/* This file is automatically generated by define_array.py */

// check NDIMS (number of spatial dimensions)
#if !defined(NDIMS)
#error "define NDIMS: -DNDIMS=2 or -DNDIMS=3"
#endif

#include "domain.h"

/*** vof ***/
#define VOF_SIZE_0 (isize+2)
#define VOF_SIZE_1 (jsize+4)
#define VOF(I, J) (vof[ (J+1) * VOF_SIZE_0 + (I  ) ])
/*** vof ***/

/*** dvof ***/
#define DVOF_SIZE_0 (isize+1)
#define DVOF_SIZE_1 (jsize+3)
#define DVOF(I, J) (dvof[ (J  ) * DVOF_SIZE_0 + (I-1) ])
/*** dvof ***/

/*** normal ***/
#define NORMAL_SIZE_0 (isize+0)
#define NORMAL_SIZE_1 (jsize+2)
#define NORMAL(I, J) (normal[ (J  ) * NORMAL_SIZE_0 + (I-1) ])
/*** normal ***/

/*** curv ***/
#define CURV_SIZE_0 (isize+0)
#define CURV_SIZE_1 (jsize+2)
#define CURV(I, J) (curv[ (J  ) * CURV_SIZE_0 + (I-1) ])
/*** curv ***/

/*** vofsrca ***/
#define VOFSRCA_SIZE_0 (isize+0)
#define VOFSRCA_SIZE_1 (jsize+0)
#define VOFSRCA(I, J) (vofsrca[ (J-1) * VOFSRCA_SIZE_0 + (I-1) ])
/*** vofsrca ***/

/*** vofsrcb ***/
#define VOFSRCB_SIZE_0 (isize+0)
#define VOFSRCB_SIZE_1 (jsize+0)
#define VOFSRCB(I, J) (vofsrcb[ (J-1) * VOFSRCB_SIZE_0 + (I-1) ])
/*** vofsrcb ***/

/*** voffluxx ***/
#define VOFFLUXX_SIZE_0 (isize+1)
#define VOFFLUXX_SIZE_1 (jsize+0)
#define VOFFLUXX(I, J) (voffluxx[ (J-1) * VOFFLUXX_SIZE_0 + (I-1) ])
/*** voffluxx ***/

/*** voffluxy ***/
#define VOFFLUXY_SIZE_0 (isize+0)
#define VOFFLUXY_SIZE_1 (jsize+1)
#define VOFFLUXY(I, J) (voffluxy[ (J-1) * VOFFLUXY_SIZE_0 + (I-1) ])
/*** voffluxy ***/

/*** voffluxz ***/
/*** voffluxz ***/

/*** voffrcx ***/
#define VOFFRCX_SIZE_0 (isize-1)
#define VOFFRCX_SIZE_1 (jsize+0)
#define VOFFRCX(I, J) (voffrcx[ (J-1) * VOFFRCX_SIZE_0 + (I-2) ])
/*** voffrcx ***/

/*** voffrcy ***/
#define VOFFRCY_SIZE_0 (isize+0)
#define VOFFRCY_SIZE_1 (jsize+0)
#define VOFFRCY(I, J) (voffrcy[ (J-1) * VOFFRCY_SIZE_0 + (I-1) ])
/*** voffrcy ***/

/*** voffrcz ***/
/*** voffrcz ***/

#endif // ARRAYS_{name}_H
