#if !defined(ARRAYS_STATISTICS_H)
#define ARRAYS_STATISTICS_H

/* This file is automatically generated by define_array.py */

// check NDIMS (number of spatial dimensions)
#if !defined(NDIMS)
#error "define NDIMS: -DNDIMS=2 or -DNDIMS=3"
#endif

#include "domain.h"

/*** ux1 ***/
#define UX1_SIZE_0 (isize+1)
#define UX1_SIZE_1 (jsize+0)
#define UX1_SIZE_2 (ksize+0)
#define UX1(I, J, K) (ux1[ (K-1) * UX1_SIZE_1 * UX1_SIZE_0 + (J-1) * UX1_SIZE_0 + (I-1) ])
/*** ux1 ***/

/*** ux2 ***/
#define UX2_SIZE_0 (isize+1)
#define UX2_SIZE_1 (jsize+0)
#define UX2_SIZE_2 (ksize+0)
#define UX2(I, J, K) (ux2[ (K-1) * UX2_SIZE_1 * UX2_SIZE_0 + (J-1) * UX2_SIZE_0 + (I-1) ])
/*** ux2 ***/

/*** uy1 ***/
#define UY1_SIZE_0 (isize+2)
#define UY1_SIZE_1 (jsize+0)
#define UY1_SIZE_2 (ksize+0)
#define UY1(I, J, K) (uy1[ (K-1) * UY1_SIZE_1 * UY1_SIZE_0 + (J-1) * UY1_SIZE_0 + (I  ) ])
/*** uy1 ***/

/*** uy2 ***/
#define UY2_SIZE_0 (isize+2)
#define UY2_SIZE_1 (jsize+0)
#define UY2_SIZE_2 (ksize+0)
#define UY2(I, J, K) (uy2[ (K-1) * UY2_SIZE_1 * UY2_SIZE_0 + (J-1) * UY2_SIZE_0 + (I  ) ])
/*** uy2 ***/

/*** uz1 ***/
#define UZ1_SIZE_0 (isize+2)
#define UZ1_SIZE_1 (jsize+0)
#define UZ1_SIZE_2 (ksize+0)
#define UZ1(I, J, K) (uz1[ (K-1) * UZ1_SIZE_1 * UZ1_SIZE_0 + (J-1) * UZ1_SIZE_0 + (I  ) ])
/*** uz1 ***/

/*** uz2 ***/
#define UZ2_SIZE_0 (isize+2)
#define UZ2_SIZE_1 (jsize+0)
#define UZ2_SIZE_2 (ksize+0)
#define UZ2(I, J, K) (uz2[ (K-1) * UZ2_SIZE_1 * UZ2_SIZE_0 + (J-1) * UZ2_SIZE_0 + (I  ) ])
/*** uz2 ***/

/*** temp1 ***/
#define TEMP1_SIZE_0 (isize+2)
#define TEMP1_SIZE_1 (jsize+0)
#define TEMP1_SIZE_2 (ksize+0)
#define TEMP1(I, J, K) (temp1[ (K-1) * TEMP1_SIZE_1 * TEMP1_SIZE_0 + (J-1) * TEMP1_SIZE_0 + (I  ) ])
/*** temp1 ***/

/*** temp2 ***/
#define TEMP2_SIZE_0 (isize+2)
#define TEMP2_SIZE_1 (jsize+0)
#define TEMP2_SIZE_2 (ksize+0)
#define TEMP2(I, J, K) (temp2[ (K-1) * TEMP2_SIZE_1 * TEMP2_SIZE_0 + (J-1) * TEMP2_SIZE_0 + (I  ) ])
/*** temp2 ***/

/*** vof1 ***/
#define VOF1_SIZE_0 (isize+2)
#define VOF1_SIZE_1 (jsize+0)
#define VOF1_SIZE_2 (ksize+0)
#define VOF1(I, J, K) (vof1[ (K-1) * VOF1_SIZE_1 * VOF1_SIZE_0 + (J-1) * VOF1_SIZE_0 + (I  ) ])
/*** vof1 ***/

/*** vof2 ***/
#define VOF2_SIZE_0 (isize+2)
#define VOF2_SIZE_1 (jsize+0)
#define VOF2_SIZE_2 (ksize+0)
#define VOF2(I, J, K) (vof2[ (K-1) * VOF2_SIZE_1 * VOF2_SIZE_0 + (J-1) * VOF2_SIZE_0 + (I  ) ])
/*** vof2 ***/

#endif // ARRAYS_{name}_H
